CREATE TABLE ANIMAL(
    CODIGO NUMBER(6) NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOME VARCHAR(30),
    DESCRICAO VARCHAR(100),
    CONSTRAINT ANIMAL_PK PRIMARY KEY (CODIGO)
);
